name: 构建v2raya镜像
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04  
    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: |
        sudo apt-get -y update
    - name: login docker
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        export DOCKER_CLI_EXPERIMENTAL=enabled
        docker buildx version
        docker run --privileged --rm docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
        docker buildx create --use --name mybuilder
        docker buildx inspect mybuilder --bootstrap
        docker buildx ls
    - name: docker v2raya
      run: |
        cd ./v2raya
        docker buildx build -t ${{ secrets.DOCKER_USERNAME }}/v2raya --platform linux/arm64,linux/amd64,linux/arm/v7 . --push
